# set TARGET_HOST to dns/ip of proxy
# set LOGSTASH_HOST to dns/ip of logstash host

proxy:
  container_name: proxy
  restart: always
  image: accenture/adop-nginx:0.1.0
  #build: ../images/docker-nginx/
  net: ${CUSTOM_NETWORK_NAME}
  ports:
    - "80:80"
    - "443:443"
  environment:
    - "constraint:tier==public"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_ATTRIBUTE=member"
    - "LDAP_USER_ID_ATTRIBUTE=cn"
    - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"

ldap:
  container_name: ldap
  restart: always
  #build: ../images/docker-ldap/
  image: accenture/adop-ldap:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "389"
  environment:
    SLAPD_PASSWORD: ${LDAP_PWD}
    SLAPD_DOMAIN: ${LDAP_DOMAIN}
    SLAPD_FULL_DOMAIN: ${LDAP_FULL_DOMAIN}

gerrit-mysql:
  container_name: gerrit-mysql
  restart: always
  image: mysql:5.6.25
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: "Password01"
    MYSQL_USER: ${GERRIT_MYSQL_USER}
    MYSQL_PASSWORD: ${GERRIT_MYSQL_PASSWORD}
    MYSQL_DATABASE: ${GERRIT_MYSQL_DATABASE}

gerrit:
  container_name: gerrit
  restart: always
  #build: ../images/docker-gerrit/
  image: accenture/adop-gerrit:0.1.0
  privileged: true
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8080"
    - "29418"
  environment:
    - "affinity:container==gerrit-mysql"
    - "REPO_PATH=/var/git/repos"
    - "WEBURL=http://${TARGET_HOST}/gerrit"
    - "DATABASE_TYPE=mysql"
    - "DB_HOSTNAME=gerrit-mysql"
    - "DB_PORT=3306"
    - "DB_NAME=${GERRIT_MYSQL_DATABASE}"
    - "DB_USER=${GERRIT_MYSQL_USER}"
    - "DB_PASSWORD=${GERRIT_MYSQL_PASSWORD}"
    - "AUTH_LOGOUTURL=http://${TARGET_HOST}/gerrit"
    - "AUTH_TYPE=LDAP"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_ACCOUNTBASE=${LDAP_FULL_DOMAIN}"
    - "LDAP_ACCOUNTPATTERN=(cn=$${username})"
    - "LDAP_ACCOUNTFULLNAME=$${cn}"
    - "LDAP_ACCOUNTEMAILADDRESS=mail"
    - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_GROUPBASE=ou=groups,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUPPATTERN=(cn=$${groupname})"
    - "LDAP_GROUPMEMBERPATTERN=(uniqueMember=$${dn})"
    - "HTTPD_LISTENURL=proxy-http://0.0.0.0:8080/gerrit"
    - "USER_NAME=${GERRIT_USER_NAME}"
    - "USER_EMAIL=${GERRIT_USER_EMAIL}"
    - "DOWNLOAD_SCHEME=http"

jenkins:
  container_name: jenkins
  restart: always
  image: johniepaulie/jenkinshost:1.0
  #build: ../images/docker-jenkins/
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8080"
    - "50000"
  privileged: true
  environment:
    JENKINS_OPTS: "--prefix=/jenkins"
    ROOT_URL: "http://${TARGET_HOST}/jenkins/"
    LDAP_SERVER: "ldap:389"
    LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
    LDAP_USER_SEARCH_BASE: "ou=people"
    LDAP_USER_SEARCH: "uid={0}"
    LDAP_GROUP_SEARCH_BASE: "ou=groups"
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_MEMBERSHIP_FILTER: ""
    LDAP_MANAGER_DN: "cn=admin,${LDAP_FULL_DOMAIN}"
    LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
    LDAP_INHIBIT_INFER_ROOTDN: "false"
    LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
    LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
    LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
    GERRIT_HOST_NAME: "gerrit"
    GERRIT_FRONT_END_URL: "http://gerrit:8080/gerrit"
    SONAR_SERVER_URL: "http://sonar:9000/sonar/"
    SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
    SONAR_ACCOUNT_PASSWORD: ${SONAR_ACCOUNT_PASSWORD}
    SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
    SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
    SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
    SONAR_PLUGIN_VERSION: ""
    SONAR_ADDITIONAL_PROPS: ""
    SONAR_RUNNER_VERSION: "2.4"
    ANT_VERSION: "1.9.4"
    MAVEN_VERSION: "3.0.5"
    NODEJS_VERSION: "0.12.2"
    NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
    NODEJS_PACKAGES_REFRESH_HOURS: "72"
    GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
    GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
    DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
    DOCKER_HOST: ${DOCKER_HOST}
    DOCKER_CLIENT_CERT_PATH: ${DOCKER_CLIENT_CERT_PATH}
    DOCKER_NETWORK_NAME: ${CUSTOM_NETWORK_NAME}
    JIRA_URL: "http://${TARGET_HOST}/jira"

jenkins-slave:
  container_name: jenkins-slave
  restart: always
  image: accenture/adop-jenkins-slave:0.1.3
  net: ${CUSTOM_NETWORK_NAME}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  environment:
    SLAVE_LABELS: "aws ldap java8 docker"
    
jira:
  container_name: jira
  restart: always
  image: johniepaulie/jirahostcentric:1.1
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8082"
  environment:
    JIRA_BASE_URL: "http://${TARGET_HOST}/jira"
